### ISSUE TITLE
Searching for spergularia yields an error

### ISSUE THREAD

**Issue by sidkoul** [newfs/gobotany-app#619] opened 2015-08-13 20:08 UTC
Searching for Spergularia or spergularia, yields "An error has occurred" page.

https://gobotany.newenglandwild.org/search/?q=spergularia

<img width="826" alt="spergularia go botany error" src="https://cloud.githubusercontent.com/assets/1482988/9260424/8b8bce12-41d5-11e5-84bb-de7edcd5b74f.png">

**Comment by jnga** [comment] 2016-06-27 18:55
Closing this issue, a duplicate of #627.

**Closed by jnga** 2016-06-27 18:55 UTC
Labels: Priority C
